### PR TITLE
Rename ETH to native token

### PR DESCRIPTION
**Pull request by fedgiac**
Replaces occurrences of ETH with "native token". Originally this contract was supposed to be deployed only on the ethereum chain, but it will also be deployed on xDai/Gnosis Chain.

No changes to the contract logic were introduced. However, the ABI of the contract will change, which means we will need to deploy a new version of the NPM package. The version bump will be done in another PR.

I left some occurrences of "ETH" in the tests because I thought it was easier to read.

### Test Plan

Existing unit tests.

### CODE REVIEW

**Review by josojo — APPROVED** [review]
eth is so much shorter than nativeToken.

Though change makes sense.
looks all correct

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
> eth is so much shorter than nativeToken.

I also thought the same thing! Good thing you don't pay gas for variable name length 😛.

Also, on a side note. @fedgiac if its not too much work, could you compare the bytecode from before the rename change to this? Might be a good way to validate that there is truly no logic changes (and satisfy my curiousity about whether or not Solidity bytecode is affected by variable names).

**Comment by fedgiac** [comment]
I'm sure there are bytecode changes as the signature of the view function `wethPrice()` changed. I could check if there are other changes however.

**Comment by fedgiac** [comment]
There are surprisingly many changes, but not enough to make me think there could be errors:
changes

I attach the bytecode files. If you want to play with it, the easiest way for me was to modify the code size benching script to print out the bytecode.
[new.txt](https://github.com/gnosis/cow-token/files/7863188/new.txt)
[old.txt](https://github.com/gnosis/cow-token/files/7863189/old.txt)

**Pull request merged**
